### ISSUE TITLE
Feature Request: HEIF/HEIC/Apple support

### ISSUE THREAD

**Issue by billbris** [drewnoakes/metadata-extractor-dotnet#231] opened 2019-11-06 00:16 UTC
1: Love the product.  It just worked!  Refreshing.
2: I would like to get at the metadata for my HEIC files from iPhone.
3: Using BitmapMetadata in System.Windows.Media.Imaging I am able to open my .JPEG's and .HEIC's and get at the metadata.  Your package is much more mature and full-featured.  Have you considered the HEIC/Apple problem space?  If so, I'm curious as to why it is not included (am I missing something).  

It just seems that the HEIC/HEIF format will be doing nothing but growing.  

I am curious as to your thoughts.

Also, love the product.

**Comment by drewnoakes** [comment] 2019-11-07 05:44
@payton implemented HEIF/HEIC support in the Java version of this library a while ago. It shouldn't be too hard to port that implementation to .NET.

https://github.com/drewnoakes/metadata-extractor/pull/314

@billbris would you like to do this?

**Comment by billbris** [comment] 2019-11-07 09:42
Let me take a peek before I commit (no pun intended).

**Comment by kastwey** [comment] 2020-01-11 06:54
Hi!

First of all, congratulations on this package, it's wonderful!
Any news about HEIF support? I'm developing a software for my blind wife to read the labels of the photos she has taken with her iPHone (and which is saved in XMP within the HEIC files) with an electron application, but I'm seeing that that part hasn't been ported to .Net yet.

Thanks in advance for the answer!

**Comment by kastwey** [comment] 2020-01-11 07:14
Hello!

First of all, congratulations on this package, it's wonderful!
Any news about HEIF support? I'm developing a software for my blind wife to read the labels of the photos she has taken with her iPHone (and which is saved in XMP within the HEIC files) with an electron application, but I'm seeing that that part hasn't been ported to .Net yet.

If nobody has started to do it, I could try it :)

Thanks in advance for the answer!

**Comment by drewnoakes** [comment] 2020-01-13 02:13
@kastwey you're most welcome to port the HEIF/HEIC support from the Java implementation to this library. The contribution would be really appreciated.

Your project sounds really interesting too. I'd like to hear more about it. Will you open source it?

**Comment by kastwey** [comment] 2020-01-13 05:36
Hi!

Perfect, I already ported all existing heif code (I think) but I've realized that the Exif and XMP support still needs to be implemented, so I'll see if I can add it (although the ISO documentation is crazy).

I'll try to do the PR during the week.

Regarding the project, yes, it will be open source. The initial interface will probably be a disaster (I'm blind too so if something gets out of place or overlaps I'll need help from someone who can see ;) ), but it will be functional :)
As soon as I release the first version, I'll let you know.

Thanks!

**Comment by drewnoakes** [comment] 2020-01-13 14:04
Great to hear you've made progress on this already. It'll be a good addition to the library as HEIC gains traction.

My early education was in a school where most of the students were blind or partially sighted. I often wonder what opportunities technology has brought to visually impaired folks, beyond the clunky mechanical Braille typewriters of the early 80's. I'll be happy to help your project however I can.

**Comment by kastwey** [comment] 2020-01-13 16:55
Hi!

You can't even imagine what technology has meant to us.
I went from a Braille typewriter (perkings), to "spoken an small
specific computer (called Braille'n speak), and from there to a laptop
with a screen reader.
From there, it's been all about technology.
Now I'm working as a team leader in a multinational, and all thanks to
the technology I use is accessible. It's just wonderful.

If you like, here's a video I shot at a Microsoft MVP event talking
about current technology for blind people.
My English was terrible, but I think it's pretty much understood :)

https://channel9.msdn.com/Events/Microsoft-Spain-Events/MVP-Summit-2017-Spain/How-to-use-accessible-tools-in-the-IT-Industry


2020-01-13 15:04 GMT+01:00, Drew Noakes <notifications@github.com>:

**Comment by mzervos** [comment] 2020-02-09 11:28
First of all, the library is great, thanks @drewnoakes and everyone who has contributed to it :)
I see that a couple of people already started working on HEIC/HEIF support. Is there an update on the progress or ETA for merging the changes?

**Comment by DrJohnMelville** [comment] 2020-04-09 16:27
This is a great library, and I would love to help.

I am about 60% of the way to a Heic parser that works so far.  I am working on it on my own fork at (https://github.com/DrJohnMelville/metadata-extractor-dotnet) although it looks like I forgot to push my commits to the server, so you cannot see any of my work right now,  (I have just about all of the Heic container format done, which requires referencing 4 or 5 differnt places on the internet because its not all written down in one place.  Once I get that done I need to map the hierarchical tree of the Heic metadata into onto the tag/value format for metadata-extractor.

Any this has been a really fun project to work on.  When I have something that actually works (probably in a week or two) I will try and figure out how to submit a pull request,

**Comment by drewnoakes** [comment] 2020-04-29 22:45
Support for HEIF/HEIC has been added in #249 by @DrJohnMelville 🎉 

@billbris @kastwey @mzervos would you (or anyone else) test out the code on `master` against some images please? We don't have many in the test data repo, so some more testing would be great.

I'd like to get this released in 2.4.0 soon.

**Comment by tipa** [comment] 2020-05-05 06:14
I tested the code with a bunch of my images (both .heic & .jpeg) and didn't observe any problems - however I was only reading the geotag, no other metadata.
Only thing I noticed is that the code crashes in `SequentialStreamReader.GetBytes` with a `System.IO.IOException: 'End of data reached.'` when I use .heic images that were previously geotagged with [this method](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.geotaghelper.setgeotagasync?view=winrt-18362). My gut feeling says that it simply produces an invalid EXIF header. Attached 3 images that were geotagged that way and cannot be read. Interestingly, Windows is able to read the geotag though (right click -> properties -> details).
[geotagged heic.zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/4579107/geotagged.heic.zip)

**Comment by drewnoakes** [comment] 2020-05-05 08:38
@tipa thanks for these, I'll check them out now. Are you willing to donate the images to [this repo](https://github.com/drewnoakes/metadata-extractor-images) for future regression testing?

**Comment by tipa** [comment] 2020-05-05 08:56
I am actually unsure regarding the licenses of the examples above, so I geotagged the heic images already present [in the repo](https://github.com/drewnoakes/metadata-extractor-images/tree/master/heic):
broken heic.zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/4579767/broken.heic.zip)

**Comment by drewnoakes** [comment] 2020-05-05 09:28
Looks like a bug in the implementation here, rather than the tool that generated the files. Caught because the Exif data was at the end of the file. The fix is on `master` in 76ea2ca5730d96782a7eab421d234433bb6fa544. Please test it out and let me know how you get on.

**Comment by tipa** [comment] 2020-05-05 10:01
Awesome, now it works!

**Comment by drewnoakes** [comment] 2020-05-05 12:29
Version 2.4.0 is now available with HEIC support. Thanks everyone!

**Closed by drewnoakes** 2020-05-05 12:29 UTC
Labels: format-heif, help wanted, image-queue

**Comment by dasunmax89** [comment] 2023-02-01 12:50
Dear all, 
first of all thanks for making this library. it saves a lot of time.
I'm having a question. I'm using it in a xamarin forms project. although it works like a charm, it cannot read gpsdirectory from metadata of a heif image.
although online metadata readers can read it, our library is unable to read. after converting to jpeg image format, it reads fine. any idea?

**Comment by drewnoakes** [comment] 2023-02-02 03:03
@dasunmax89 can you please open a new issue and attach an image that contains the data, so that we can investigate on an actual image? Do you have an image you can donate (publicly) to the project for analysis and regression testing?
