### ISSUE TITLE
VS2017 / C# 7 support

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor-dotnet#93] opened 2017-03-15 15:37 UTC
Last week VS2017 was released along with C# 7.

Does anyone have any reservations about the project upgrading? This would cause the solution to not _build_ under VS2015, however you could still use the NuGet package in earlier version(s) of Visual Studio just fine.

**Comment by kwhopper** [comment] 2017-03-15 15:42
I'm all for it. VS2017 Community is free anyway if people need to build. Microsoft will likely stop updating VS2015 very soon (if they haven't already) as they did with 2013, and newer .NET Core support might start to dwindle there as well.

That said - you'll have to be careful that C# 7 support doesn't push the .NET Framework version requirement further than you want it to go.

**Comment by drewnoakes** [comment] 2017-03-15 15:46
Agreed -- we wouldn't change the minimum framework requirement at all.

**Comment by twest820** [comment] 2017-03-18 15:39
The projects were upgraded to VS2017 yesterday and no longer open in VS2015.3.  However, my VS2017 RTM install is unable to locate any of the tests after a debug or retail build or completes.  The xunit packages installed without issue and VS does see [Fact] as a test marker, enabling Run Tests in the method's right click menu.  But it then doesn't execute any test and produces no test output indicating the cause of the failure.  Known issue?  I checked the wiki but didn't see any instructions about any additional setup requirements and I've other projects where VS2017 runs the tests fine.

With the x86 test engine:
------ Load Playlist started ------
========== Load Playlist finished (0:00:00.0040037) ==========
------ Discover test started ------
========== Discover test finished: 0 found (0:01:01.3259922) ==========

With the x64 test engine:
------ Discover test started ------
Test run will use DLL(s) built for framework Framework45 and platform X64. Following DLL(s) will not be part of run: 
MetadataExtractor.Benchmarks.exe is built for Framework Framework45 and Platform X86.
 Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
========== Discover test finished: 0 found (0:01:03.7143222) ==========

**Comment by drewnoakes** [comment] 2017-03-18 18:22
@twest820 could you try again now that #100 has been merged?

**Comment by twest820** [comment] 2017-03-18 19:50
No observable difference, unfortunately.  Microsoft did already put out a patch the VS2017 installer and RTM bits Friday.  But updating to VS 15.0.26228.9 actually kind of makes the issue worse; test discovery now has a tendency to loop continuously and constantly fail rather than running and just failing once per build.  It's also unclear why discovery is so slow; spends the whole minute per attempt with VS at 2-3% CPU, so I'm wondering if maybe something's hanging/failing early on and then a 1 minute timeout fires to abort the process.

------ Discover test started ------
========== Discover test finished: 0 found (0:01:00.4615985) ==========
------ Discover test started ------
========== Discover test finished: 0 found (0:01:04.8870016) ==========
------ Discover test started ------
========== Discover test finished: 0 found (0:01:01.0010287) ==========
...

This may be one of the active VS2017 or xunit test discovery issues such as https://github.com/Microsoft/vstest/issues/629 or https://github.com/xunit/xunit/issues/1140.  Kicking off dotnet test from the command line suggests xunit might be looking for tests in the wrong place:

dotnet-test Error: 0 : System.InvalidOperationException: Metadata Extractor\MetadataExtractor.Tests\project.json does not exist.
   at Microsoft.DotNet.Tools.Test.TestCommand.GetProjectPath(String projectPath)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)

**Comment by drewnoakes** [comment] 2017-03-18 20:04
Interesting. I'm not seeing any problem here, but I'm using ReSharper's test runner.

`dotnet test` is working for me too.

<details>
<summary>Output from `dotnet test`</summary>

```

$ dotnet test
Build started, please wait...
Build completed.

Test run for C:\Users\Drew\dev\metadata-extractor-dotnet\MetadataExtractor.Tests\bin\Debug\netcoreapp1.0\MetadataExtractor.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.7481606]   Discovering: MetadataExtractor.Tests
[xUnit.net 00:00:01.0687676]   Discovered:  MetadataExtractor.Tests
[xUnit.net 00:00:01.1761991]   Starting:    MetadataExtractor.Tests
[xUnit.net 00:00:01.7266768]     MetadataExtractor.Tests.DirectoryTest.SetStringGetInt [SKIP]
[xUnit.net 00:00:01.7268561]       TODO test whether this is needed in a regression test against the image database
Skipped  MetadataExtractor.Tests.DirectoryTest.SetStringGetInt
[xUnit.net 00:00:01.7483744]     MetadataExtractor.Tests.Formats.Exif.ExifReaderGremlinTest.DoesntThrowNoMatterWhat [SKIP]
[xUnit.net 00:00:01.7484348]       Don't run on CI machines as it takes an age to complete
Skipped  MetadataExtractor.Tests.Formats.Exif.ExifReaderGremlinTest.DoesntThrowNoMatterWhat
[xUnit.net 00:00:01.8048982]   Finished:    MetadataExtractor.Tests

Total tests: 249. Passed: 247. Failed: 0. Skipped: 2.
Test Run Successful.
Test execution time: 2.9137 Seconds


Test run for C:\Users\Drew\dev\metadata-extractor-dotnet\MetadataExtractor.Tests\bin\Debug\net452\MetadataExtractor.Tests.dll(.NETFramework,Version=v4.5.2)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.4837224]   Discovering: MetadataExtractor.Tests
[xUnit.net 00:00:00.9500049]   Discovered:  MetadataExtractor.Tests
[xUnit.net 00:00:01.4388710]   Starting:    MetadataExtractor.Tests
[xUnit.net 00:00:02.7784615]     MetadataExtractor.Tests.DirectoryTest.SetStringGetInt [SKIP]
[xUnit.net 00:00:02.7786318]       TODO test whether this is needed in a regression test against the image database
Skipped  MetadataExtractor.Tests.DirectoryTest.SetStringGetInt
[xUnit.net 00:00:03.1985569]     MetadataExtractor.Tests.Formats.Exif.ExifReaderGremlinTest.DoesntThrowNoMatterWhat [SKIP]
[xUnit.net 00:00:03.1986351]       Don't run on CI machines as it takes an age to complete
Skipped  MetadataExtractor.Tests.Formats.Exif.ExifReaderGremlinTest.DoesntThrowNoMatterWhat
[xUnit.net 00:00:03.4628201]   Finished:    MetadataExtractor.Tests

Total tests: 251. Passed: 249. Failed: 0. Skipped: 2.
Test Run Successful.
Test execution time: 3.8120 Seconds
```
</details>

<details><summary>Output of `dotnet --info`</summary>

```
$ dotnet --info
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```
</details>

**Comment by drewnoakes** [comment] 2017-03-18 21:18
@twest820 are you running `dotnet test` from the `MetadataExtractor.Tests` directory?

**Comment by twest820** [comment] 2017-03-18 23:27
May not be relevant.  My dev machine did have a 1.0.0-preview2 install from December which the VS2017 installer didn't clean.  Removing the preview and repairing VS2017 has no effect on test discovery failure but it did remove dotnet.  When it was installed I got the same results regardless of directory.  Similarly, the %TEMP%\VisualStudioTestExplorerExtensions guidance at http://xunit.github.io/docs/getting-started-desktop#run-tests-visualstudio has no effect.  Though, after several attempts VS did actually suggest xunit's getting pinged called for test discovery:

------ Discover test started ------
\AppData\Local\Temp\VisualStudioTestExplorerExtensions\2.2.0/build/netcoreapp1.0/xunit.runner.visualstudio.dotnetcore.testadapter.dll
========== Discover test finished: 0 found (0:00:01.7072139) ==========

So one possibility is VS is looking in the .NET Core build for tests but discovery fails around xunit dependency management.  From the nuget dependency stack I would expect to see xunit.abstractions.dll, xunit.assert.dll, xunit.core.dll, and an xunit.execution.*.dll in MetadataExtractor.Test\bin\Debug\netcoreapp1.0 but these assemblies aren't copied.  If I put variations of them over manually then the console runner fails on framework assembly loading.  Don't have time to investigate further at the moment but it's unclear if this case is currently supported as [the xunit .NET Core docs are retracted](https://xunit.github.io/docs/getting-started-dotnet-core.html).

Metadata Extractor> .nuget\packages\xunit.runner.console\2.2.0\tools\xunit.console.exe MetadataExtractor.Tests\bin\Debug\net452\MetadataExtractor.Tests.dll
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: MetadataExtractor.Tests
  Discovered:  MetadataExtractor.Tests
  Starting:    MetadataExtractor.Tests
    MetadataExtractor.Tests.Formats.Exif.ExifReaderGremlinTest.DoesntThrowNoMatterWhat [SKIP]
      Don't run on CI machines as it takes an age to complete
    MetadataExtractor.Tests.DirectoryTest.SetStringGetInt [SKIP]
      TODO test whether this is needed in a regression test against the image database
  Finished:    MetadataExtractor.Tests
=== TEST EXECUTION SUMMARY ===
   MetadataExtractor.Tests  Total: 251, Errors: 0, Failed: 0, Skipped: 2, Time: 0.828s

Metadata Extractor> .nuget\packages\xunit.runner.console\2.2.0\tools\xunit.console.exe MetadataExtractor.Tests\bin\Debug\netcoreapp1.0\MetadataExtractor.Tests.dll
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
System.InvalidOperationException: Unknown test framework: could not find xunit.dll (v1) or xunit.execution.*.dll (v2) in Metadata Extractor\MetadataExtractor.Tests\bin\Debug\netcoreapp1.0

**Comment by twest820** [comment] 2017-03-19 04:48
OK, the missing piece is the .NET Core cross-platform deployment workload needs to be installed.  The same hello world issue was [reported November 18, 2016](https://developercommunity.visualstudio.com/content/problem/2903/net-core-test-projects-fail-to-discover-tests.html) and marked as fixed in VS2017 RC; apparently it's either regressed in RTM or has multiple causes.  (My guess would be a package dependency for the .NET development workload is misconfigured.)

**Closed** 2017-04-19 19:04 UTC
